###
# Find All Books
GET http://localhost:3000/books

###
# Find User By Id
GET http://localhost:3000/book/2

###
# Create Book using ID
POST http://localhost:3000/book
Content-Type: application/json

{
  "title": "Fuego y Sangre 2",
  "isbn": "1072345",
  "author" : 1
}

###
# Create Book using author details
POST http://localhost:3000/book
Content-Type: application/json

{
  "title": "Spy School the Graphic Novel 3",
  "isbn": "1534455426azxv",
  "author" : {
    "firstname": "Stuart",
    "lastname": "Gibbs"
  }
}


###
# Modify User By Id
PUT http://localhost:3000/book/17
Content-Type: application/json

{
  "isbn": "23439584fgas"
}



###
# This probably must fail
PUT http://localhost:3000/book/1993824454564
Content-Type: application/json

{
  "isbn": "492385453645"
}



###
# Delete User By Id
DELETE http://localhost:3000/book/17
